Add missing checkInterval to k8s deployment config
As is, the example k8s agent fails to deploy, going into a CrashLoopBackoff:

```
{"level":"info","ts":1589972770.1904275,"caller":"builder/exporters_builder.go:95","msg":"Exporter started.","component_kind":"exporter","component_type":"otlp","component_name":"otlp"}
Error: cannot setup pipelines: cannot build pipelines: error creating processor "memory_limiter" in pipeline "traces": checkInterval must be greater than zero
2020/05/20 11:06:10 Application run finished with error: cannot setup pipelines: cannot build pipelines: error creating processor "memory_limiter" in pipeline "traces": checkInterval must be greater than zero
```

caveat: as I couldn't find documentation and am just looking around right now, I don' really know if 5s is a sensible value at all ;)